[versions]
compileSdk = "36"
minSdk = "26"

agp = "8.13.0"
autofill = "1.3.0"
argon2kt = "1.6.0"
camera = "1.5.0"
credentials = "1.6.0-beta03"
gmsMlkitBarcodeScanning = "18.3.1"
okhttp = "5.1.0"
zxingBarcodeScanning = "3.5.3"
kotlin = "2.2.20"
kotlinSerializationJson = "1.9.0"
collectionsImmutable = "0.4.0"
coreKtx = "1.17.0"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.11.0"
composeBom = "2025.09.01"
mockk = "1.14.6"
semver = "0.2.5"
koinBOM = "4.1.1"
koinAnnotationsBOM = "2.2.0"
room = "2.8.1"
ksp = "2.2.20-2.0.2"
datastore = "1.1.7"
protobuf = "0.9.5"
protoc = "4.32.1"
coroutinesTest = "1.10.2"
bcrypt = "0.10.2"
biometric = "1.4.0-alpha04"
navigation = "2.9.5"
kotlinpoet = "2.2.0"
nbvcxz = "1.5.1"
totp = "2.4.1"
passGen = "0.1.0-beta"

[libraries]
argon2kt = { module = "com.lambdapioneer.argon2kt:argon2kt", version.ref = "argon2kt" }
google-protobuf-protoc = { group = "com.google.protobuf", name = "protoc", version.ref = "protoc" }
google-protobuf-kotlin-lite = { group = "com.google.protobuf", name = "protobuf-kotlin-lite", version.ref = "protoc" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit", version.ref = "kotlin" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutinesTest" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinSerializationJson" }
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "collectionsImmutable" }

androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version = "1.5.0-alpha04" }

androidx-material3-adaptive-navigation = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation" }
androidx-material3-adaptive-navigation-suite = { group = "androidx.compose.material3", name = "material3-adaptive-navigation-suite" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }

androidx-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-biometric = { group = "androidx.biometric", name = "biometric", version.ref = "biometric" }

androidx-autofill = { group = "androidx.autofill", name = "autofill", version.ref = "autofill" }
androidx-credentials = { group = "androidx.credentials", name = "credentials", version.ref = "credentials" }

androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camera" }
androidx-camera-compose = { module = "androidx.camera:camera-compose", version.ref = "camera" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camera" }

koin-bom = { group = "io.insert-koin", name = "koin-bom", version.ref = "koinBOM" }
koin-annotations-bom = { group = "io.insert-koin", name = "koin-annotations-bom", version.ref = "koinAnnotationsBOM" }
koin-core = { group = "io.insert-koin", name = "koin-core" }
koin-annotations = { group = "io.insert-koin", name = "koin-annotations" }
koin-ksp-compiler = { group = "io.insert-koin", name = "koin-ksp-compiler", version.ref = "koinAnnotationsBOM" }
koin-androidx-compose = { group = "io.insert-koin", name = "koin-androidx-compose" }

androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

androidx-datastore = { group = "androidx.datastore", name = "datastore", version.ref = "datastore" }

at-favre-bcrypt = { group = "at.favre.lib", name = "bcrypt", version.ref = "bcrypt" }

google-devtools-ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
io-mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
squareup-kotlinpoet = { group = "com.squareup", name = "kotlinpoet-ksp", version.ref = "kotlinpoet" }

okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }

gosimple-nbvcxz = { group = "me.gosimple", name = "nbvcxz", version.ref = "nbvcxz" }
turingcomplete-totp = { group = "dev.turingcomplete", name = "kotlin-onetimepassword", version.ref = "totp" }

offrange-passgen = { group = "com.github.offrange", name = "passgen", version.ref = "passGen" }

gms-mlkit-barcode-scanning = { group = "com.google.android.gms", name = "play-services-mlkit-barcode-scanning", version.ref = "gmsMlkitBarcodeScanning" }
zxing-barcode-scanning = { group = "com.google.zxing", name = "core", version.ref = "zxingBarcodeScanning" }

[plugins]
google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
google-protobuf = { id = "com.google.protobuf", version.ref = "protobuf" }
android-application = { id = "com.android.application", version.ref = "agp" }
androidx-room = { id = "androidx.room", version.ref = "room" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
git-semantic-versioning = { id = "io.github.offrange.git-semantic-versioning", version.ref = "semver" }
android-library = { id = "com.android.library", version.ref = "agp" }

