[package]
name = "lib"
version = "0.1.0"
edition = "2024"

[dependencies]
aead = "0.6.0"
aes-gcm-siv = "0.12.1"
async-trait = "0.1.89"
ciborium = "0.2.2"
coset = "0.4.2"
ed25519-dalek = { version = "3.0.0", features = ["rand_core"] }
passkey = "0.5.0"
passkey-authenticator = { version = "0.5.0", features = ["tokio", "testable"] }
# Needed so passkey JSON responses are serialized into base64 strings
passkey-types = { version = "0.5.0", features = ["serialize_bytes_as_base64_string"] }

base64 = "0.23.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
thiserror = "2.0.18"
url = "2.5.8"
zeroize = "1.8.2"
uuid = { version = "1.23.0", features = ["serde", "v4"] }
rand = { version = "0.10.0", features = ["sys_rng"] }
bcs = "0.2.0"
argon2 = "0.5.3"
hkdf = "0.13.0"
sha2 = "0.11.0"
totp-rs = { version = "5.7.1", features = ["otpauth", "zeroize", "serde_support"] }
csv = "1.4.0"
email_address = "0.2.9"
base32 = "0.5.1"
